### ISSUE TITLE
Divide filelists and generate config.json & Generate hubert and f0 errors

### ISSUE THREAD

**Issue by Ai-Artsca** [justinjohn0306/so-vits-svc-4.0-v2#2]
I wanted to bring to your attention some errors I encountered while trying to run your code on colab. I hope this feedback helps you improve your project.

The first error I encountered was a FileNotFoundError in the preprocess_flist_config.py file. The traceback is as follows:

Traceback (most recent call last):
File "/content/so-vits-svc/preprocess_flist_config.py", line 38, in <module>
for speaker in tqdm(os.listdir(args.source_dir)):
FileNotFoundError: [Errno 2] No such file or directory: './dataset/44k'

The second error I encountered was also a FileNotFoundError, this time in the utils.py file. The traceback is as follows:

Traceback (most recent call last):
File "/content/so-vits-svc/preprocess_hubert_f0.py", line 17, in <module>
hps = utils.get_hparams_from_file("configs/config.json")
File "/content/so-vits-svc/utils.py", line 412, in get_hparams_from_file
with open(config_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/config.json'

I suggest checking the file paths to make sure they are correct and the necessary files are present. Please let me know if you need any further information from my end.

Thank you for your time and effort in developing this project.

**Comment by jagilley** [comment]
I also encountered this — thanks!

**Comment by jagilley** [comment]
@Ai-Artsca this happens if your .zip directory structure has an extra layer between the .zip and the actual .wav files. The Colab is kinda confusing, but your .wav files should be at the top folder of the .zip. Just throw some wavs in a folder, zip it, and you're good to go.

@justinjohn0306 this issue can probably be closed.
